const SEQUENCE_PREFIX = {
  APPOINTMENTS_SEQUENCE: {
    APPOINTMENTS_MODEL: "appointments",
    SEQUENCE: "VYDAPMT",
  },
};

exports.SEQUENCE_PREFIX = SEQUENCE_PREFIX;
exports.TIME_SLOT_INTERVAL = 20;